fix compilation with dsp 0.9.26.13026
hubastard/nebula pull request #573
Opened 2022-06-17 23:57 UTC by starfi5h

## TODO
- Fix error when client selecting a different planet as birth planet
- Show vein amount for client in lobby
- Sync vein amount when client viewing existing factories

2022-06-19 11:35 UTC, Fank requested changes

2022-06-19 11:35 UTC, Fank commented on NebulaNetwork/PacketProcessors/Planet/PlanetDetailRequestProcessor.cs
> +                    if (planetData.type != EPlanetType.Gas)
I think you can combine the two `if` cases

2022-06-19 23:48 UTC, SirDeadlystrike commented
June 17th's update breaks the published version of this mod.

Built this branch in release mode as of hash `3049212` to restore functionality and played with a small group. 

Worked great, the only bug we found was an issue with constructing blueprints and drones not wanting to fly to and build random parts unless you walked directly onto of them, tho I don't think thats an issue with this specific branch.

2022-06-20 19:38 UTC, PhantomGamers approved these changes
LGTM

2022-06-20 19:43 UTC, merged